#!/usr/bin/env python
# -*- coding: utf-8 -*-
###########################################################
#               WARNING: Generated code!                  #
#              **************************                 #
# Manual changes may get lost if file is generated again. #
# Only code inside the [MANUAL] tags will be kept.        #
###########################################################

from flexbe_core import Behavior, Autonomy, OperatableStateMachine, ConcurrencyContainer, PriorityContainer, Logger
from o2ac_flexbe_states.insertion import InsertActionState
from o2ac_flexbe_states.orient import OrientActionState
from o2ac_flexbe_states.pick import PickActionState
# Additional imports can be added inside the following tags
# [MANUAL_IMPORT]

# [/MANUAL_IMPORT]


'''
Created on 1635746453102
@author: AUTOGENERATED
'''
class subtask_c2SM(Behavior):
	'''
	Behavior extracted from PDDL trace: subtask_c2
	'''


	def __init__(self):
		super(subtask_c2SM, self).__init__()
		self.name = 'subtask_c2'

		# parameters of this behavior

		# references to used behaviors

		# Additional initialization code can be added inside the following tags
		# [MANUAL_INIT]
		
		# [/MANUAL_INIT]

		# Behavior comments:



	def create(self):
		# x:30 y:395, x:480 y:540
		_state_machine = OperatableStateMachine(outcomes=['failed', 'finished'])

		# Additional creation code can be added inside the following tags
		# [MANUAL_CREATE]
		
		# [/MANUAL_CREATE]


		with _state_machine:
			# x:30 y:40
			OperatableStateMachine.add('1: pick a_bot end_cap ',
										PickActionState(robot_name="a_bot", object_name="end_cap", helper_robot_name=""),
										transitions={'success': '2: pick b_bot shaft ', 'error': 'failed'},
										autonomy={'success': Autonomy.Off, 'error': Autonomy.Off})

			# x:80 y:130
			OperatableStateMachine.add('2: pick b_bot shaft ',
										PickActionState(robot_name="b_bot", object_name="shaft", helper_robot_name=""),
										transitions={'success': '3: orient b_bot  shaft', 'error': 'failed'},
										autonomy={'success': Autonomy.Off, 'error': Autonomy.Off})

			# x:130 y:220
			OperatableStateMachine.add('3: orient b_bot  shaft',
										OrientActionState(robot_name="b_bot", task_name="", object_name="shaft"),
										transitions={'success': '4: orient a_bot  end_cap', 'error': 'failed'},
										autonomy={'success': Autonomy.Off, 'error': Autonomy.Off})

			# x:180 y:310
			OperatableStateMachine.add('4: orient a_bot  end_cap',
										OrientActionState(robot_name="a_bot", task_name="", object_name="end_cap"),
										transitions={'success': '5: insert-dual-arm a_bot end_cap shaft  b_bot', 'error': 'failed'},
										autonomy={'success': Autonomy.Off, 'error': Autonomy.Off})

			# x:230 y:400
			OperatableStateMachine.add('5: insert-dual-arm a_bot end_cap shaft  b_bot',
										InsertActionState(robot_name="a_bot", object_name="end_cap", target="shaft", task_name="", helper_robot_name="b_bot"),
										transitions={'success': '6: insert b_bot shaft bearing  ', 'error': 'failed'},
										autonomy={'success': Autonomy.Off, 'error': Autonomy.Off})

			# x:280 y:490
			OperatableStateMachine.add('6: insert b_bot shaft bearing  ',
										InsertActionState(robot_name="b_bot", object_name="shaft", target="bearing", task_name="", helper_robot_name=""),
										transitions={'success': 'finished', 'error': 'failed'},
										autonomy={'success': Autonomy.Off, 'error': Autonomy.Off})


		return _state_machine


	# Private functions can be added inside the following tags
	# [MANUAL_FUNC]
	
	# [/MANUAL_FUNC]
