robot_name: b_bot
waypoints:
- pose_type: joint-space-goal-cartesian-lin-motion
  speed: 0.5
  pose: [1.70955, -1.76188, 2.20655, -2.03371, -1.54722, 0.21328]
  blend: 0.01
  is_trajectory: True
- pose_type: joint-space-goal-cartesian-lin-motion
  speed: 0.5
  pose: [1.83711, -2.03315, 2.54636, -2.08639, -1.54045, 0.28342]
  blend: 0.01
- pose_type: joint-space-goal-cartesian-lin-motion
  speed: 0.5
  pose: [1.83603, -1.86888, 2.6557, -2.35998, -1.54055, 1.48353]
  blend: 0.0
  is_trajectory: True
- pose_type: gripper
  gripper:
    action: open
    opening_width: 0.07
- pose_type: joint-space-goal-cartesian-lin-motion
  speed: 0.7
  pose: [1.83602, -1.86889, 2.65576, -2.35999, -1.54056, -0.08881]
- pose_type: gripper
  gripper:
    action: close-open
    opening_width: 0.07
- pose_type: joint-space-goal-cartesian-lin-motion
  speed: 0.7
  pose: [1.83601, -1.86894, 2.65587, -2.36008, -1.5406, -1.66107]
- pose_type: joint-space-goal-cartesian-lin-motion
  speed: 0.7
  pose: [1.36839, -1.8889, 2.70104, -2.08534, -1.13864, -2.1986]
- pose_type: gripper
  gripper:
    action: close
- pose_type: joint-space-goal-cartesian-lin-motion
  speed: 0.3
  pose: [1.3899, -2.097, 2.5718, -1.7734, -1.1517, -2.1679]
