# Define the points in the trajectory
robot_name: 'b_bot' # for security define the robot here
waypoints:
- pose: [-0.15, 0, 0.10, -90, 0, 0] # translation, orientation (degrees)
  pose_type: task-space-in-frame
  frame_id: right_centering_link
  speed: 0.5
  desc: Above tray edge
- pose: [-0.05, 0, 0.0, -100, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: right_centering_link
  speed: 0.5
  is_trajectory: True
  blend: 0.005
  desc: Above centering point
- pose: [-0.02, 0, 0.0, -100, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: right_centering_link
  speed: 0.2
  is_trajectory: True
  blend: 0.0
  desc: dropping 
- pose_type: gripper
  gripper:
    action: 'open'
    open_width: 0.07
    velocity: 0.1
- pose: [-0.02, 0, 0.0, -10, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: right_centering_link
  speed: 2.0
- pose_type: gripper
  gripper:
    action: 'close-open'
    open_width: 0.07
    velocity: 0.05
  desc: Centering 
- pose: [-0.022, 0, 0.0, -100, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: right_centering_link
  speed: 2.0
- pose: [0.0, 0, 0, 0, -52, 0] 
  pose_type: relative-tcp
  speed: 1.0
- pose_type: gripper
  gripper:
    action: 'close'
    velocity: 0.05
- pose: [0.0, 0, 0.04, 0, 0, 0] 
  pose_type: relative-world
  speed: 0.2
- pose: [0.0, 0, 0.0, 0, 103, 0] 
  pose_type: relative-tcp
  speed: 0.6
- pose: [0.0, 0, -0.035, 0, 0, 0] 
  pose_type: relative-world
  speed: 0.2
- pose_type: gripper
  gripper:
    action: 'open'
    open_width: 0.07
    velocity: 0.1
- pose: [0.0, 0.0, 0.0, 0, -103, 0] 
  pose_type: relative-tcp
- pose_type: gripper
  gripper:
    action: 'close'
    velocity: 0.05
- pose: [0.0, 0, 0.05, 0, 0, 0] 
  pose_type: relative-world
  speed: 0.3
- pose: [-0.025, 0, 0.0, -100, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: right_centering_link
  speed: 0.5
  desc: dropping
- pose_type: gripper
  gripper:
    action: 'open'
    open_width: 0.07
    velocity: 0.1
- pose: [-0.02, 0, 0.0, -10, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: right_centering_link
  speed: 2.0
- pose_type: gripper
  gripper:
    action: 'close-open'
    open_width: 0.07
    velocity: 0.05
  desc: Centering 
- pose: [-0.02, 0, 0.0, -100, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: right_centering_link
  speed: 2.0
- pose: [0.0, 0, 0.005, 0, -35, 0] 
  pose_type: relative-tcp
  speed: 1.0
- pose_type: gripper
  gripper:
    action: 'close'
    velocity: 0.05
- pose: [0.0, 0, 0.05, 0, 0, 0] 
  pose_type: relative-world
  speed: 0.5
  desc: move up
- pose: [-0.15, 0, 0.10, -100, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: right_centering_link
  is_trajectory: True
  blend: 0.005
  speed: 1.0
- pose: [-0.038, -0.001, 0.005, 0, -35.0, 0] 
  pose_type: task-space-in-frame
  frame_id: default
  speed: 1.0
  is_trajectory: True
  blend: 0.0
  desc: near tb 
- pose: [-0.017, 0.000, 0.002, 0, -35.0, 0] 
  pose_type: task-space-in-frame
  frame_id: default
  speed: 1.0
  is_trajectory: True
  blend: 0.0
  desc: pre insertion 
