# Define the points in the trajectory
robot_name: 'b_bot' # for security define the robot here
waypoints:
- pose: [-0.15, 0, 0.10, 0, 0, 0] # translation, orientation (degrees)
  pose_type: task-space-in-frame
  frame_id: right_centering_link
  speed: 0.5
  is_trajectory: True
  blend: 0.005
  desc: Above tray edge
- pose: [-0.05, 0, 0.0, -100, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: right_centering_link
  speed: 0.5
  is_trajectory: True
  blend: 0.005
  desc: Above centering point
- pose: [-0.01, 0, 0.0, -100, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: right_centering_link
  speed: 0.2
  is_trajectory: True
  blend: 0.0
  desc: dropping 
- pose_type: gripper
  gripper:
    action: 'open'
    open_width: 0.07
- pose: [-0.01, 0, 0.0, -10, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: right_centering_link
  speed: 0.5
- pose_type: gripper
  gripper:
    action: 'close-open'
    open_width: 0.07
  desc: Centering 
- pose: [-0.01, 0, 0.0, -100, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: right_centering_link
  speed: 0.5
- pose: [0.0, 0, 0, 0, -55, 0] 
  pose_type: relative-tcp
- pose_type: gripper
  gripper:
    action: 'close'
- pose: [0.0, 0, 0.04, 0, 0, 0] 
  pose_type: relative-world
- pose: [0.0, 0, 0.0, 0, 100, 0] 
  pose_type: relative-tcp
- pose: [0.0, 0, -0.03, 0, 0, 0] 
  pose_type: relative-world
- pose_type: gripper
  gripper:
    action: 'open'
    open_width: 0.07
- pose: [0.0, 0, 0.0, 0, -100, 0] 
  pose_type: relative-tcp
- pose_type: gripper
  gripper:
    action: 'close'
- pose: [0.0, 0, 0.05, 0, 0, 0] 
  pose_type: relative-world
- pose: [-0.01, 0, 0.0, -100, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: right_centering_link
  speed: 0.2
  desc: dropping
- pose_type: gripper
  gripper:
    action: 'open'
    open_width: 0.07
- pose: [-0.01, 0, 0.0, -10, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: right_centering_link
  speed: 0.5
- pose_type: gripper
  gripper:
    action: 'close-open'
    open_width: 0.07
  desc: Centering 
- pose: [-0.01, 0, 0.0, -100, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: right_centering_link
  speed: 0.5
- pose: [0.0, 0, 0.005, 0, -35, 0] 
  pose_type: relative-tcp
- pose_type: gripper
  gripper:
    action: 'close'
- pose: [-0.05, 0, 0.0, -100, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: right_centering_link
  is_trajectory: True
  blend: 0.005
  speed: 0.5
- pose: [-0.15, 0, 0.10, -100, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: right_centering_link
  is_trajectory: True
  blend: 0.005
  speed: 0.5
- pose: [-0.038, -0.001, 0.005, 0, -35.0, 0] 
  pose_type: task-space-in-frame
  frame_id: default
  speed: 1.0
  is_trajectory: True
  blend: 0.0
  desc: near tb 
- pose: [-0.012, -0.001, 0.004, 0, -35.0, 0] 
  pose_type: task-space-in-frame
  frame_id: default
  speed: 1.0
  is_trajectory: True
  blend: 0.0
  desc: pre insertion 
