# Define the points in the trajectory
robot_name: 'a_bot' # for security define the robot here
waypoints:
- pose: [-0.15, 0, -0.10, -90, 0, 0] # translation, orientation (degrees)
  pose_type: task-space-in-frame
  frame_id: left_centering_link
  speed: 1.0
  desc: Above tray edge
- pose: [-0.07, 0, 0.02, -90, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: left_centering_link
  speed: 0.7
  is_trajectory: True
  blend: 0.01
  desc: Above centering point
- pose: [-0.02, 0, 0.02, -90, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: left_centering_link
  speed: 0.2
  is_trajectory: True
  blend: 0.0
  desc: dropping 
- pose_type: gripper
  gripper:
    action: 'open'
    open_width: 0.07
    velocity: 0.1
- pose: [-0.02, 0, 0.02, -10, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: left_centering_link
  speed: 1.0
- pose_type: gripper
  gripper:
    action: 'close-open'
    open_width: 0.07
    velocity: 0.05
  desc: Centering 
- pose: [-0.022, 0, 0.02, -90, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: left_centering_link
  speed: 1.0
- pose: [0.0, 0, 0, 0, -30, 0] 
  pose_type: relative-tcp
  speed: 0.8
- pose_type: gripper
  gripper:
    action: 'close'
    velocity: 0.05
- pose: [0.0, 0, 0.04, 0, 0, 0] 
  pose_type: relative-world
  speed: 0.1
- pose: [0.0, 0, 0.0, 0, 103, 0] 
  pose_type: relative-tcp
  speed: 0.3
- pose: [0.0, 0, -0.035, 0, 0, 0] 
  pose_type: relative-world
  speed: 0.1
- pose_type: gripper
  gripper:
    action: 'open'
    open_width: 0.07
    velocity: 0.1
- pose: [0.0, 0.0, 0.0, 0, -103, 0] 
  pose_type: relative-tcp
  speed: 0.3
- pose_type: gripper
  gripper:
    action: 'close'
    velocity: 0.05
- pose: [0.0, 0, 0.05, 0, 0, 0] 
  pose_type: relative-world
  speed: 0.1
- pose: [-0.025, 0, 0.02, -90, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: left_centering_link
  speed: 0.5
  desc: dropping
- pose_type: gripper
  gripper:
    action: 'open'
    open_width: 0.07
    velocity: 0.1
- pose: [-0.02, 0, 0.02, 60, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: left_centering_link
  speed: 1.0
- pose_type: gripper
  gripper:
    action: 'close-open'
    open_width: 0.07
    velocity: 0.05
  desc: Centering 
- pose: [-0.02, 0, 0.02, -30, 0, 0] 
  pose_type: task-space-in-frame
  frame_id: left_centering_link
  speed: 1.0
- pose: [0.0, 0, 0.005, 0, 35, 0] 
  pose_type: relative-tcp
  speed: 1.0
- pose_type: gripper
  gripper:
    action: 'close'
    velocity: 0.05
- pose: [0.0, 0, 0.05, 0, 0, 0] 
  pose_type: relative-world
  speed: 0.1
  desc: move up
