robot_name: a_bot
waypoints:
- pose: [-0.15, 0, 0.0, 0, 0, 0]
  pose_type: relative-tcp
  speed: 0.2
- pose: 'home'
  pose_type: named-pose
  speed: 0.2
- pose_type: gripper
  gripper:
    action: open
    velocity: 0.1
- desc: above_nut_aid
  pose: [1.7012, -1.9212, 1.788, -1.4422, -1.5809, 3.2784]
  pose_type: joint-space
  speed: 0.2
- desc: at_nut_aid
  pose: [0.0, 0, -0.25, 0, 0, 0]
  pose_type: relative-base
  speed: 0.2
- pose_type: gripper
  gripper:
    action: close
    velocity: 0.05
- pose: [0.0, 0, 0.25, 0, 0, 0]
  pose_type: relative-base
  speed: 0.2
  # above_nut_aid
