extra_frames:
- pose_xyzrpy:
  - 0.075
  - 0.0
  - 0.0
  - -pi/2
  - 0.0
  - 0.0
  subframe_name: front_tip
- pose_xyzrpy:
  - 0.026
  - 0.0
  - 0.0
  - pi/2
  - 0.0
  - pi
  subframe_name: inserted
- pose_xyzrpy:
  - 0.0
  - 0.0
  - 0.0
  - pi/2
  - 0.0
  - pi
  subframe_name: back_tip
grasp_points: []
