extra_frames:
- pose_xyzrpy:
  - 0.006
  - 0.0
  - 0.015
  - -pi/2
  - 0.0
  - -pi/2
  subframe_name: bottom_screw_hole_aligner_1
- pose_xyzrpy:
  - 0.11
  - 0.0
  - 0.015
  - -pi/2
  - 0.0
  - -pi/2
  subframe_name: bottom_screw_hole_aligner_2
- pose_xyzrpy:
  - 0.006
  - 0.005
  - 0.015
  - -pi/2
  - 0.0
  - -pi/2
  subframe_name: bottom_screw_hole_1
- pose_xyzrpy:
  - 0.11
  - 0.005
  - 0.015
  - -pi/2
  - 0.0
  - -pi/2
  subframe_name: bottom_screw_hole_2
- pose_xyzrpy:
  - 0.035
  - 0.04
  - 0.0
  - -pi/2
  - -pi/2
  - 0.0
  subframe_name: front_hole
- pose_xyzrpy:
  - 0.095
  - 0.05
  - 0.0
  - -pi/2
  - -pi/2
  - 0.0
  subframe_name: pulley_ridge_bottom
- pose_xyzrpy:
  - 0.095
  - 0.065
  - 0.0
  - -pi/2
  - -pi/2
  - 0.0
  subframe_name: pulley_ridge_middle
- pose_xyzrpy:
  - 0.095
  - 0.08
  - 0.0
  - -pi/2
  - -pi/2
  - 0.0
  subframe_name: pulley_ridge_top
grasp_points: []
