camera_type: RealSenseCamera
camera_name: b_bot_outside_camera
robot_name: b_bot
eye_on_hand: true
robot_base_frame: workspace_center
robot_effector_frame: b_bot_ee_link
camera_frame: calibrated_b_bot_outside_camera_color_optical_frame
marker_id: 17
marker_size: 0.07
planarity_tolerance: 0.003
initpose: [-0.10, 0.20, 0.35, -90, 90, 90]
keyposes:
  - [-0.23,  0.10, 0.35, -90,  60,  0]
  - [-0.18,  0.10, 0.35, -90,  75,  0]
  - [-0.10,  0.10, 0.35, -90,  90,  0]
  - [-0.02,  0.10, 0.35, -90, 105,  0]
  - [ 0.03,  0.10, 0.35, -90, 120,  0]
  - [-0.10,  0.05, 0.35,   0,  75, 90]
  - [-0.10,  0.05, 0.35,   0,  80, 90]
  - [-0.10,  0.20, 0.35,   0, 110, 90]
  - [-0.10,  0.25, 0.35,   0, 120, 90]

camera_body_frame: b_bot_outside_camera_link
camera_optical_frame: b_bot_outside_camera_color_optical_frame
