# This file contains metadata about the assembly.
description: The "known" assembly set announced for the WRS2020 

bearing_panel_facing_backward: False
motor_panel_facing_backward: False
switched_motor_and_bearing: False

motor_shaft_down: False
