parts_list:
  - id: 1
    name: base_plate
    cad: taskboard_01_base.stl
    description: Base Panel
  - id: 2
    name: task_plate
    cad: taskboard_02_plate.stl
    description: L plate
  - id: 3
    name: taskboard_idler_pulley_small
    cad: MBGNA30-2.stl
    description: Small idler pulley with mounted axis
  - id: 4
    name: taskboard_idler_pulley_large
    cad: MBGNA60-2.stl
    description: Idley pulley (not used)
  - id: 5
    name: motor_pulley
    type: 05_MBRFA30-2-P6
    cad: 05_MBRFA30-2-P6.stl
    description: Pulley for Round Belt (4mm) - Setscrew P.D. 30mm
  - id: 6
    name: drive_shaft
    cad: shaft_KZAF1075NA4WA55GA20AA0.stl
    description: Shaft for the bearing
  - id: 7
    name: bearing
    type: 07_SBARB6200ZZ-30
    cad: 07_SBARB6200ZZ_30.stl
    description: Bearings with Housings (Double Bearings)
  - id: 8
    name: endcap
    type: endcap_EDCS10
    cad: endcap_EDCS10.stl
    description: End Cap for Shaft
