dt: 0.002 # 500Hz
position:
  p: [1., 1., 1., 2.5, 2.5, 2.5]
  d: 'default'
  i: 'default'
  dynamic: True # Caution: makes the p-gain variable
force:
  p: [0.05, 0.05, 0.05, 5.0, 5.0, 5.0]
  d: 'default'
  i: 'default'
  dynamic: False
selection_matrix: [1., 1., 1., 1., 1., 1.] # 1: position control, 0: force control, any value in between is a compromise of position and force
max_force_torque: [50., 50., 50., 5., 5., 5.] # try to avoid emergency stops with a lower max force torque 
