localization_parameters:
  01-BASE:
    size: [0.200, 0.120]
    origin: [-0.100, 0.060, 0.0, 90.0, 0.0, 0.0]
    rotation_range: [0.0, 360.0, 45.0]
    refine_transform: true
  02-PANEL:
    size: [0.070, 0.060]
    origin: [-0.035, -0.030, 0.0, 0.0, 0.0, 0.0]
    rotation_range: [0.0, 360.0, 45.0]
    refine_transform: true
  03-PANEL2:
    size: [0.116, 0.090]
    origin: [-0.058, -0.045, 0.0, 0.0, 0.0, 0.0]
    rotation_range: [0.0, 360.0, 45.0]
    refine_transform: true
  04_37D-GEARMOTOR-50-70:
    size: [0.054, 0.037]
    origin: [-0.0185, 0.0, 0.0185, 90.0, 0.0, 0.0]
    rotation_range: [0.0, 180.0, 15.0]
    refine_transform: true
  05_MBRFA30-2-P6:
    size: [0.030, 0.030]
    origin: [0.0, 0.0, 0.005, 0.0, 90.0, 0.0]
    rotation_range: [0.0, 0.0, 0.0]
    refine_transform: true
  06_MBT4-400:
    size: [0.127, 0.127]
    origin: [0.0, 0.0, 0.003, 0.0, 0.0, 0.0]
    rotation_range: [0.0, 0.0, 0.0]
    refine_transform: false
  07_SBARB6200ZZ_30:
    size: [0.054, 0.054]
    origin: [0.0, 0.0, 0.0, 0.0, 90.0, 0.0]
    rotation_range: [0.0, 0.0, 0.0]
    refine_transform: true
  08_KZAF1075NA4WA55GA20AA0:
    size: [0.075, 0.010]
    origin: [-0.0375, 0.0, 0.005, 0.0, 0.0, 0.0]
    rotation_range: [0.0, 0.0, 0.0]
    refine_transform: false
  09_EDCS10:
    size: [0.010, 0.010]
    origin: [0.0, 0.0, 0.0, 0.0, -90.0, 0.0]
    rotation_range: [0.0, 0.0, 0.0]
    refine_transform: false
  10_CLBPS10_17_4:
    size: [0.017, 0.017]
    origin: [0.0, 0.0, 0.0, 0.0, -90.0, 0.0]
    rotation_range: [0.0, 0.0, 0.0]
    refine_transform: false
  11_MBRAC60-2-10:
    size: [0.062, 0.062]
    origin: [0.0, 0.0, 0.005, 0.0, -90.0, 0.0]
    rotation_range: [0.0, 0.0, 0.0]
    refine_transform: true
  12_CLBUS6-9-9.5:
    size: [0.006, 0.006]
    origin: [0.0, 0.0, 0.0, 0.0, -90.0, 0.0]
    rotation_range: [0.0, 0.0, 0.0]
    refine_transform: false
  13_MBGA30-2:
    size: [0.030, 0.030]
    origin: [0.0, 0.0, 0.0, 0.0, -90.0, 0.0]
    rotation_range: [0.0, 0.0, 0.0]
    refine_transform: true
  14_BGPSL6-9-L30-F8:
    size: [0.033, 0.006]
    origin: [-0.016, 0.0, 0.003, 0.0, 0.0, 0.0]
    rotation_range: [0.0, 0.0, 0.0]
    refine_transform: true
  15_SLBNR6:
    size: [0.0062, 0.0062]
    origin: [0.0, 0.0, 0.0025, 0.0, 90.0, 0.0]
    rotation_range: [0.0, 0.0, 0.0]
    refine_transform: false
